"""Initial migration.

Revision ID: 61b212e06683
Revises: 
Create Date: 2022-07-06 12:45:05.889515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b212e06683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('user_type',
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_type_id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('news_heading', sa.String(), nullable=False),
    sa.Column('news_info', sa.String(), nullable=False),
    sa.Column('news_date', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('scraped_data', sa.Boolean(), nullable=True),
    sa.Column('news_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_category_id'], ['news_category.category_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('has_premium', sa.Boolean(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.user_type_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('journalist_news_mapping',
    sa.Column('journalist_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journalist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ),
    sa.PrimaryKeyConstraint('journalist_id', 'news_id')
    )
    op.create_table('news_image_mapping',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ),
    sa.PrimaryKeyConstraint('news_id', 'image')
    )
    op.create_table('premium_user_mapping',
    sa.Column('premium_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('premium_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium_user_mapping')
    op.drop_table('news_image_mapping')
    op.drop_table('journalist_news_mapping')
    op.drop_table('user')
    op.drop_table('news')
    op.drop_table('user_type')
    op.drop_table('news_category')
    # ### end Alembic commands ###
