"""empty message

Revision ID: 954f5b666da1
Revises: cfb835cf5723
Create Date: 2022-06-15 15:03:58.215186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954f5b666da1'
down_revision = 'cfb835cf5723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=20), nullable=False))
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fname', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('lname', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
