name: news ci
env:
  HEROKU_API_KEY: a4d0bd7b-1949-4bad-ad97-209f672643b7 

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run -m pytest
  
  deploy:
    stage: deploy
    script:
      - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/news-to-read.git
      - git push heroku master
      - echo "Deployed to Server https://news-to-read.herokuapp.com"
    environment:
      name: staging
      url: https://news-to-read.herokuapp.com/

  