name: Push to DockerHub

env:
  DOCKER_USERNAME: "ocean02"
  DOCKER_PASSWORD: "*xV8.m47j:gJRg-"

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    docker:
      run-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3        
        - name: Login to docker
          run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        - name: Build docker image
          run: |
            docker build -t ocean02/news-to-read:dev .

        - name: Push docker image to docker registry
          run: |
            docker push ocean02/news-to-read:dev