name: Push to DockerHub


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3        
      - name: Login to docker
        run: |
          docker login -u ocean03 -p *xV8.m47j:gJRg-

      - name: Build docker image
        run: |
          docker build -t ocean03/news-to-read:dev .

      - name: Push docker image to docker registry
        run: |
          docker login
          docker push ocean03/news-to-read:dev