name: Push to DockerHub


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3        
      - name: Login to docker
        run: |
          docker login -u ocean03 -p *xV8.m47j:gJRg-

      - name: Build docker image
        run: |
          docker build -t ocean03/news-to-read:dev .

      - name: Push docker image to docker registry
        run: |
          docker login
          docker push ocean03/news-to-read:dev
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_SECRET_KEY }}
          app: ${{ secrets.HEROKU_APP }}

          dockerfile_directory: .
          dockerfile_name: Dockerfile
          docker_option: "--no-cache"
          process_type: web